### ISSUE TITLE
can someone send me a compiled, clean version with no bugs such as S_Sound?

### ISSUE THREAD

**Issue by Chris2918** [CKFDevPowered/CKF3Alpha#5]
I keep getting the S_Sound error, can someone give me a clean compiled versions with no bugs?

**Comment by Chris2918** [comment]
Anything really?

**Comment by lucastheguyy** [comment]
https://steamcommunity.com/groups/ckf3community/discussions/3/3344417177390992794/

**Comment by Chris2918** [comment]
Thank you
